# Generated by Django 5.0.3 on 2024-03-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
